# Site settings
author: Ghameerah McCullers
title: Getting Acquainted with Web Dev
header-img: img/home-bg.png
email: mccullers.ghameerah@gmail.com
copyright_name: Ghameerah McCullers
description: > # this means to ignore newlines until "baseurl:"
  Dismantling a tech giant
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: ghameerah
github_username:  ameerrah9

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
